---
output:
  html_document:
    number_sections: no
    toc: no
    code_folding: show
runtime: shiny
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
library(knitr)
library(tidyverse)
library(dplyr)
library(tidyr)
library(plotly)
library(foreign)
library(shiny)
library(ggplot2)
library(maps)
```

```{r}
data <- read.csv("Inequality in Education.csv")
# colnames(data)
```

```{r}
# Subset data for first graph:
# Group countries by UNDP Dev. Regions and compute mean for each year
df_region_mean <- data %>%
  group_by(`UNDP.Developing.Regions`) %>%
  summarize(across(starts_with("Inequality.in.Education"), mean, na.rm = TRUE))

# Reshape data for plotting
df_region_mean_long <- df_region_mean %>%
  pivot_longer(cols = starts_with("Inequality.in.Education"), names_to = "Year", values_to = "Average_Inequality")

# Extract the year from the column names
df_region_mean_long$Year <- gsub("Inequality.in.Education..(\\d+)\\.", "\\1", df_region_mean_long$Year)
```

```{r}
# Subset data for second graph:
# Convert "Inequality in Education" columns to numeric
inequality_columns <- grep("Inequality.in.Education", names(data), value = TRUE)
data[inequality_columns] <- lapply(data[inequality_columns], as.numeric)

# Create a melted version of the dataframe for interactive visualization
# HDI stands for Human Development Index (HDI)
df_melted <- data %>%
  select('Country', 'Human.Development.Groups', 'UNDP.Developing.Regions', 'HDI.Rank..2021.', 
         'Inequality.in.Education..2010.', 'Inequality.in.Education..2011.',
         'Inequality.in.Education..2012.', 'Inequality.in.Education..2013.',
         'Inequality.in.Education..2014.', 'Inequality.in.Education..2015.',
         'Inequality.in.Education..2016.', 'Inequality.in.Education..2017.',
         'Inequality.in.Education..2018.', 'Inequality.in.Education..2019.',
         'Inequality.in.Education..2020.', 'Inequality.in.Education..2021.') %>%
  pivot_longer(cols = starts_with("Inequality.in.Education"), 
               names_to = "Year", 
               values_to = "Inequality.in.Education") %>%
  mutate(Year = as.integer(gsub("\\D", "", Year)))
```

```{r}
# Subset data for third graph:

world <- map_data("world")

# worldSubset <- inner_join(world, df_melted, by = "region")
```

```{r}
# Map Formatting
plain <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_rect(fill = "white"),
  plot.title = element_text(hjust = 0.5),
  legend.title = element_blank()
)
```

```{r}
ui <- fluidPage(
  titlePanel("DS 2003: Final Project on Education Inequality"),
  HTML("<p>By: Joseph Choe, Tu-Yen Dang, Eunice Kim, Herin Seo, Philip Yao</p>"),
  tabsetPanel(
    
    # INTRODUCTION TAB
    tabPanel("Introduction",
      HTML("
        <h2>Background</h2>
          <p>Education is a fundamental human right and a key driver of social and economic development. However, access to quality education is not equally distributed across the world, and many people face significant barriers and disadvantages that prevent them from realizing their full potential.</p>
          <p>This report may interest global educational officials, like the heads of the US Department of Education or the UK's Secretary of State for Education, who want to see how much education can affect a country's standard of life. Our results will offer them an opportunity to compare their systems with other nations, and explore ways to enhance their education (or share their methods with other nations), striving for equitable and improved education globally.</p>
             
        <h2>Dataset</h2>
          <p>Found on Kaggle, the data used for this report was the Inequality in Education Around the World data set, which collected data from over 196 countries. The data was derived and developed from the Human Development Reports. With the dataset, this report will look at the relationship between education with global regions, and where they stand in how well they excel in lifestyles.</p>
          <li>Link to data source: https://www.kaggle.com/datasets/iamsouravbanerjee/inequality-in-education-around-the-world</li>
          <li>Link to Human Development Reports site: https://hdr.undp.org/</li>
          <h3>Columns</h3>
            <p>We found all the columns in the data set useful for our analysis. Below is a description of each of the columns:</p>
            <li>`Country`: name of country observed</li>
            <li>`Human.Development.Groups`: Categorical rating for Human Development (very high, high, medium, and low) (Based on the Human Development Reports</li>
            <li>`UNDP.Developing.Regions`: UNDP Developing Regions, including: Sub-Saharan Africa (SSA), Latin America and the Caribbean (LAC), East Asia and the Pacific (EAP), Arab States (AS), Europe and Central Asia (ECA), South Asia (SA)</li>
            <li>`HDI.Rank..2021`: Human Development Index Rank for 2021 (Based on the Human Development Reports)</li>
            <li>Inequality.in.Education..2010` through `Inequality.in.Education..2021: Inequality for Education for the respective year. This was measured using the Atkinson index, resulting in a percentage value, where a higher percentage indicates higher inequality.</li>


        
        <h2>Questions</h2>
          <p>After exploring the data set and the subject of this report, we proposed two research questions to investigate:</p>
          <li>How does education inequality affect a country's human development rank, and how has it progressed throughout the years?</li>
          <li>What are the trends in education inequality in a certain geographical region?</li>
      ")
    ),
    
    # EDA/DESCRIPTIVES TAB
    tabPanel("EDA",
             ### NEED TO DO ###
    ),
    
    # SCATTER PLOT TAB
    tabPanel("Scatter Plot",
      sidebarLayout(
        sidebarPanel(
          checkboxGroupInput("regions_checkbox", "Select Regions:", 
            choices = setdiff(unique(data$UNDP.Developing.Regions), ""), 
            selected = unique(data$UNDP.Developing.Regions)),
          HTML("
            <p>Caption: This is a scatter plot graph that addresses the first research question. It is a plot that graphs each country based on its HDI Rank in 2021 (x-axis), and their inequality in education rate (y-axis). The country's point colors also represent the Human Development Group each country is identified as. Users can then decide what year they want the plot to display, and if they would like to remove or add certain countries based on their UNDP Developing Regions.</p>
          ")
        ),
        mainPanel(
          plotlyOutput("scatter_plot")
        )
      )
    ),
    
    # LINE PLOT TAB
    tabPanel("Line Plot",
      sidebarLayout(
        sidebarPanel(
          selectInput("region_input", "Select Region:", choices = unique(df_region_mean_long$`UNDP.Developing.Regions`), selected="AS"),
          sliderInput("slider_year", "Select Year Range:",
                  min = as.numeric(min(df_region_mean_long$Year)), 
                  max = as.numeric(max(df_region_mean_long$Year)),
                  value = c(as.numeric(min(df_region_mean_long$Year)), as.numeric(max(df_region_mean_long$Year))),
                  step = 1,
                  sep = ""),
          checkboxInput("show_points", "Show Points", TRUE),
          HTML("
               <p>Caption: This line graph addresses the second research question, showcasing the average education inequality rate within a selected region, based on the user's choice. The x-axis denotes the years in which the average was calculated, while the y-axis illustrates the average education inequality. Users have the flexibility to specify a range of years for analysis and toggle the display of individual data points on the graph, providing a customizable exploration of the dataset.</p>
               ")
        ),
        mainPanel(
          plotOutput("line_plot")
        )
      )
    ),
    
    # MAP TAB
    tabPanel("Map Graph",
      sidebarLayout(
        sidebarPanel(
          sliderInput("inequality", "Inequality Level:", min = 0, max = 50, value = c(0, 5), step = 5),
          radioButtons("year", "Year:", choices = c("2010","2011","2012","2013","2014","2015","2016","2017","2018", "2019", "2020", "2021"), selected = "2021"),
          HTML("
               <p>Caption: This world map graph visually represents global education inequality data, addressing the second question. The interactive map enables users to select a specific year for analysis and an inequality range spanning from 0 to 50. It illustrates education inequality rates across countries by employing color gradation, effectively showcasing the disparities. Unlike the line plot, this map provides a comprehensive view, allowing simultaneous visualization of the entire dataset and facilitating a broader understanding of regional differences..
               ")
        ),
        mainPanel(
          plotOutput("worldHDI")
        )
      )
    ),
    
    # CONCLUSION TAB
    tabPanel("Conclusion",
      HTML("
        <h2>Chart Analysis</h2>
        <p>Graph One Observations:</p>
            <ul>
            <li>Generally, it can be seen that the HDI group the countries are in generally stays in their respective ranges in HDI ranking. The major differences lie in the inequality in education rate.<li>
              <ul>
              <li>The very high categorized countries can be seen fluctuating significantly in the earlier years (2010-2016), whereas in later years, less change occurs in this group.</li>
              <li>The high categorized countries also had a decent amount of fluctuation between 2010 through 2018. The medium categorized countries also followed that trend.</li>
              <li>The low tiered countries had fairly minimal fluctuation. It was still visible, but there were a lot less movement in education inequality rates throughout the years.</li>
              </ul>
              </ul>

        <p> Graph 2 & 3 Observations: Over time, the regions experienced the following decreases in education inequality:</p>
          <ul>
          <li>South Asia (SA): high and steady inequality value of 37.8 up until 2016, where there is a significant drop down to 33. From there, the average education inequality remains around that value.</li>
          <li>Sub-Saharan Africa (SSA): fluctuates from 33.5-34 from 2010-2018. At 2019, there was a significant drop down to 32.5.</li>
          <li>Europe and Central Asia (ECA): steady decline (almost logarithmic) from 9.5 to 5.75.</li>
          <li>Arab States (AS): steady decline (logarithmic) from 32.7 to 23.5.</li>
          <li>Latin America and the Caribbean (LAC): steady decline (logarithmic) from 19 to 15.1.</li>
          <li>East Asia and Pacific (EAP): lots of fluctuation in between, but there's an overall decline from 19.5 to 15.1.</li>
          </ul>

        <h2>Summary</h2>
          <li> A higher education inequality has a positive correlation with a country's human development rank, suggesting that a higher education equality results the country succeeding more with their standard of living.</li>
          <li> The most significant changes in ranks occurred among countries classified in the very high HDI category, whereas minimal movement was observed in the low HDI rankings concerning education inequality.</li>
          <li>Regionally, it can be seen that each region decreased their education inequality overtime. Some achieved this in a steady manners, while others in a more drastic change, but they have all put efforts into having more and better educational opportunities.</li>
        <h2>Challenges and Limitations</h2>
          <p>Missing values: This dataset contained a decent number of missing values (over 200). For the line plot and world map, the missing values didn't drastically affect the values, since individual countries itselves were not observed. However, this was an initial concern with the scatter plot. In the end though, we chose to not include those data points rather than fill them with 0s and inaccurately skew the graph.</p>
        <h2>Citations</h2>
          <ul>
          <li>Human Development Reports: https://hdr.undp.org/ </li>
          <li>Inequality in Education Data Set: https://www.kaggle.com/datasets/iamsouravbanerjee/inequality-in-education-around-the-world </li>
      ")
    )
  )
)
```

```{r}
server <- function(input, output) {
  # Filter data based on selected region and slider values, excluding rows with NAs
  filtered_data <- reactive({
    req(input$region_input)
    df_region_mean_long %>%
      filter(`UNDP.Developing.Regions` == input$region_input,
        as.numeric(Year) >= input$slider_year[1],
        as.numeric(Year) <= input$slider_year[2])
  })
  
  # RENDER SCATTER PLOT
  output$scatter_plot <- renderPlotly({
    selected_regions <- input$regions_checkbox
    filtered_data_scatter <- df_melted %>%
      filter(`UNDP.Developing.Regions` %in% selected_regions)
    
    fig <- filtered_data_scatter %>%
      plot_ly(x = ~`HDI.Rank..2021.`, 
              y = ~`Inequality.in.Education`, 
              color = ~`Human.Development.Groups`,
              frame = ~Year, 
              text = ~Country,
              type = 'scatter',
              mode = 'markers',
              marker = list(size = 10),
              range = list(y = c(0, max(filtered_data_scatter$`Inequality.in.Education`) + 5))) %>%
      layout(title = 'Inequality in Education vs HDI Rank (2010-2021)',
             xaxis = list(title = 'HDI Rank (2021)'),
             yaxis = list(title = 'Inequality in Education'),
             autosize = FALSE,
             width = 800,
             height = 600)
    fig
  })
  
  # RENDER LINE PLOT
  output$line_plot <- renderPlot({
    gg <- ggplot(data = filtered_data(), aes(x = as.factor(Year), y = Average_Inequality, group = `UNDP.Developing.Regions`, color = `UNDP.Developing.Regions`)) +
      geom_line() +
      labs(title = paste("Average Inequality in Education by UNDP Region (", input$slider_year[1], "-", input$slider_year[2], ") -", input$region_input),
           x = "Year",
           y = "Average Inequality in Education") +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
      scale_color_discrete(name = "UNDP Developing Region")
    if (input$show_points) {
      gg <- gg + geom_point()
    }
    gg
  })

  # RENDER WORLD MAP
  output$worldHDI <- renderPlot({
    worldSubset_filtered <- worldSubset %>% 
      filter(Inequality.in.Education >= input$inequality[1] & Inequality.in.Education <= input$inequality[2] & Year == input$year)
    worldHDI <- ggplot(data = worldSubset, mapping = aes(x = long, y = lat, group = group)) + 
      coord_fixed(1.3) +
      geom_polygon(aes(fill = Inequality.in.Education)) +
      geom_polygon(data = worldSubset_filtered, fill = NA, color = "black") +
      scale_fill_distiller(palette ="RdBu", direction = -1) +
      ggtitle("Inequality in Education") +
      theme_void() 
    print(worldHDI)
  })
}

# Run Shiny App
shinyApp(ui, server)
```
